# Generated by Django 4.1.7 on 2023-04-04 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ocasiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='foto',
        ),
        migrations.AlterField(
            model_name='produtos',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.categorias'),
        ),
        migrations.CreateModel(
            name='ProdutosFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='produtos')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produtos')),
            ],
        ),
        migrations.AddField(
            model_name='produtos',
            name='cor',
            field=models.ManyToManyField(to='loja.cor'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='loja.genero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='loja.marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='ocasiao',
            field=models.ManyToManyField(to='loja.ocasiao'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='tamanho',
            field=models.ManyToManyField(to='loja.tamanho'),
        ),
    ]
