# Generated by Django 4.1.7 on 2023-04-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_cor_genero_marca_ocasiao_tamanho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='produtos',
            name='cor',
            field=models.ManyToManyField(null=True, to='loja.cor'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='ocasiao',
            field=models.ManyToManyField(null=True, to='loja.ocasiao'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='tamanho',
            field=models.ManyToManyField(null=True, to='loja.tamanho'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='categoria',
            field=models.ManyToManyField(null=True, to='loja.categorias'),
        ),
    ]
