# Generated by Django 4.1.7 on 2023-04-04 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_remove_produtos_categoria_alter_produtos_cor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='produtos',
            name='cor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='loja.cor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='tamanho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='loja.tamanho'),
            preserve_default=False,
        ),
    ]
