# Generated by Django 4.1.7 on 2023-04-06 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_peca_prodtamcorqtd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidositens',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.prodtamcorqtd'),
        ),
        migrations.AlterField(
            model_name='produtosfoto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.peca'),
        ),
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
