# Generated by Django 4.1.7 on 2023-04-06 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_alter_pedidositens_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='produtos')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.cor')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.peca')),
            ],
        ),
        migrations.CreateModel(
            name='TamQtd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_estoque', models.PositiveIntegerField()),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.corfoto')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.tamanho')),
            ],
        ),
        migrations.RemoveField(
            model_name='prodtamcorqtd',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='prodtamcorqtd',
            name='peca',
        ),
        migrations.RemoveField(
            model_name='prodtamcorqtd',
            name='tamanho',
        ),
        migrations.DeleteModel(
            name='ProdutosFoto',
        ),
        migrations.AlterField(
            model_name='pedidositens',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.tamqtd'),
        ),
        migrations.DeleteModel(
            name='ProdTamCorQtd',
        ),
    ]
