# Generated by Django 4.2 on 2023-04-20 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_corfoto_tamqtd_remove_prodtamcorqtd_cor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='coresDisponiveis',
            field=models.ManyToManyField(to='loja.cor'),
        ),
        migrations.AddField(
            model_name='peca',
            name='tamDisponiveis',
            field=models.ManyToManyField(to='loja.tamanho'),
        ),
        migrations.CreateModel(
            name='ProdutoCompleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.peca')),
            ],
        ),
    ]
